version: '3.4'
services:
  easyadmin.server:
    image: ${DOCKER_REGISTRY-}easyadminserver
    build:
      context: .
      dockerfile: EasyAdmin/Server/Dockerfile
    links:
      - db
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./appsettings.json:/app/appsettings.json
      - ./templates:/app/Services/Mailer/Templates
    depends_on:
      - db
    ports:
      - 8080:80
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: easyadmin
  
